command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"
  - --server.address
  - "0.0.0.0"

env:
  - name: JIRA_API_TOKEN
    valueFrom: secret/ric-pulse/jira-token
  - name: JIRA_SERVER
    value: "https://esimplicity.atlassian.net"
  - name: MS_GRAPH_CLIENT_ID
    valueFrom: secret/ric-pulse/graph-client-id
  - name: MS_GRAPH_CLIENT_SECRET
    valueFrom: secret/ric-pulse/graph-client-secret
  - name: MS_GRAPH_TENANT_ID
    valueFrom: secret/ric-pulse/graph-tenant-id
